version: "3.8"

services:
  remix:
    image: app-dremix1-node:latest
    build:
      context: ./docker/node
      args:
        UID: 1000
        GID: 1000
        USER_NAME: dev
    user: 1000:1000
    volumes:
      - ./source:/app
    ports:
      - 3000:3000
    command:
      - npm
      - run
      - dev
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - my_network

  db:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kostya@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - my_network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  my_network:
    driver: bridge
